'use client';

import { motion } from 'framer-motion';
import { WobbleCard } from '@/components/ui/wobble-card';

export function FeaturesGrid() {
  const features = [
    {
      id: 1,
      title: "AI that guides your interview, real-time",
      description: "IntervuAI uses the screen, transcript, and AI to answer questions and suggest follow-ups for you, live.",
      bgColor: "#234C6A",
      image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600&h=400&fit=crop&q=80",
    },
    {
      id: 2,
      title: "Instant follow-up emails",
      description: "Send perfectly drafted follow-up emails within seconds after every interview.",
      bgColor: "#456882",
    },
    {
      id: 3,
      title: "Who are you really interviewing?",
      description: "Learn everything about candidates before every call—where they work, what they do, and more.",
      bgColor: "#1B3C53",
    },
    {
      id: 4,
      title: "Beautiful interview notes",
      description: "Instant shareable interview notes generated by AI.",
      bgColor: "#1B3C53",
      image: "https://images.unsplash.com/photo-1542744095-291d1f67b221?w=600&h=400&fit=crop&q=80",
    },
  ];

  return (
    <section className="relative py-20 px-4 md:px-8 lg:px-16">
      <div className="max-w-7xl mx-auto">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white mb-4">
            Four ways we make your
            <br />
            interviews better
          </h2>
        </motion.div>

        {/* Features Grid - Asymmetric Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 max-w-7xl mx-auto w-full items-stretch">
          {/* Card 1 - Large spanning 2 columns */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="col-span-1 lg:col-span-2 h-full"
          >
            <WobbleCard
              containerClassName={`h-full min-h-[500px] lg:min-h-[300px] overflow-visible`}
              className="relative overflow-visible"
              style={{ backgroundColor: features[0].bgColor }}
            >
              <div className="max-w-xs relative z-10">
                <h2 className="text-left text-balance text-base md:text-xl lg:text-3xl font-semibold tracking-[-0.015em] text-white">
                  {features[0].title}
                </h2>
                <p className="mt-4 text-left text-base/6 text-neutral-200">
                  {features[0].description}
                </p>
              </div>
              {/* Image peeking through */}
              <motion.img
                src={features[0].image}
                alt={features[0].title}
                width={400}
                height={400}
                initial={{ 
                  x: 150, 
                  opacity: 0,
                  scale: 0.8
                }}
                whileInView={{ 
                  x: 0, 
                  opacity: 1,
                  scale: 1
                }}
                viewport={{ once: true, margin: "-100px" }}
                transition={{ 
                  duration: 0.8, 
                  delay: 0.3,
                  type: "spring",
                  stiffness: 100,
                  damping: 15
                }}
                className="absolute -right-10 lg:-right-20 grayscale -bottom-8 lg:-bottom-12 object-cover rounded-2xl z-20 pointer-events-none w-[250px] h-[250px] lg:w-[350px] lg:h-[350px]"
                style={{ 
                  display: 'block'
                }}
                onLoad={() => {
                  console.log('✅ Pink image loaded successfully');
                }}
                onError={(e) => {
                  console.error('❌ Pink image failed to load:', features[0].image);
                }}
              />
            </WobbleCard>
          </motion.div>

          {/* Card 2 - Small single column */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="col-span-1 h-full"
          >
            <WobbleCard 
              containerClassName={`h-full min-h-[500px] lg:min-h-[300px]`}
              style={{ backgroundColor: features[1].bgColor }}
            >
              <h2 className="max-w-80 text-left text-balance text-base md:text-xl lg:text-3xl font-semibold tracking-[-0.015em] text-white">
                {features[1].title}
              </h2>
              <p className="mt-4 max-w-[26rem] text-left text-base/6 text-neutral-200">
                {features[1].description}
              </p>
            </WobbleCard>
          </motion.div>

          {/* Card 3 - Small single column */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="col-span-1 h-full"
          >
            <WobbleCard 
              containerClassName={`h-full min-h-[500px] lg:min-h-[300px]`}
              style={{ backgroundColor: features[2].bgColor }}
            >
              <h2 className="max-w-80 text-left text-balance text-base md:text-xl lg:text-3xl font-semibold tracking-[-0.015em] text-white">
                {features[2].title}
              </h2>
              <p className="mt-4 max-w-[26rem] text-left text-base/6 text-neutral-200">
                {features[2].description}
              </p>
            </WobbleCard>
          </motion.div>

          {/* Card 4 - Large spanning 2 columns */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="col-span-1 lg:col-span-2 h-full"
          >
            <WobbleCard
              containerClassName={`h-full min-h-[500px] lg:min-h-[300px] overflow-visible`}
              className="overflow-visible"
              style={{ backgroundColor: features[3].bgColor }}
            >
              <div className="max-w-sm relative z-10">
                <h2 className="max-w-sm md:max-w-lg text-left text-balance text-base md:text-xl lg:text-3xl font-semibold tracking-[-0.015em] text-white">
                  {features[3].title}
                </h2>
                <p className="mt-4 max-w-[26rem] text-left text-base/6 text-neutral-200">
                  {features[3].description}
                </p>
              </div>
              {/* Image peeking through */}
              <motion.img
                src={features[3].image}
                alt={features[3].title}
                width={400}
                height={400}
                initial={{ 
                  x: 150, 
                  opacity: 0,
                  scale: 0.8
                }}
                whileInView={{ 
                  x: 0, 
                  opacity: 1,
                  scale: 1
                }}
                viewport={{ once: true }}
                transition={{ 
                  duration: 0.8, 
                  delay: 0.5,
                  type: "spring",
                  stiffness: 100,
                  damping: 15
                }}
                className="absolute -right-10 lg:-right-20 bottom-8 lg:bottom-12 object-cover rounded-2xl z-20 pointer-events-none w-[250px] h-[250px] lg:w-[350px] lg:h-[350px]"
                style={{ 
                  display: 'block'
                }}
                onError={(e) => {
                  console.error('❌ Blue image failed to load:', features[3].image);
                }}
              />
            </WobbleCard>
            </motion.div>
        </div>
      </div>
    </section>
  );
}
