services:
  media-service:
    build: .
    image: media-service:latest
    container_name: media-service
    ports:
      - "5004:5004"
    env_file:
      - .env
    environment:
      # Fallbacks if not in .env
      - SERVER_HOST= "0.0.0.0"
      - SERVER_PORT= "5004"
      # - UPLOAD_FOLDER= "/app/uploads"
      - UPLOAD_FOLDER= "/app/temp/uploads"
      - MAX_CONTENT_LENGTH_BYTES= "524288000"
      - CORS_ORIGINS= "*"
      # Set a strong token in .env for production!
      - ADMIN_TOKEN= "${ADMIN_TOKEN:?set-in-.env}"
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/skillscreen_database
      - PYTHONPATH=/app:/common-service
    volumes:
      - ./backend/media-service:/app
      # - ./Users/mukulgarg/Downloads/AIP_backup/video_recordings:/app/uploads
      - ./backend/common-service:/common-service
      # - /Users/mukulgarg/Downloads/AIP_backup/video_recordings:/app/uploads
    restart: unless-stopped
